// Prix en DH (converti en centimes ×100 au moment de l'insertion).
// Calculé depuis commandes_2026-06-03_18-04-53.csv (11 203 commandes réelles),
// puis corrigé manuellement : les grandes villes (Marrakech, Tanger, Rabat,
// Fes, Agadir, Meknes, Kenitra, Sale, Oujda, El jadida, Mohammedia, Tetouan,
// Safi, Beni mellal, Temara) sont à 30 DH, Casablanca reste à 20 DH.
// Par défaut toute ville absente de cette liste reçoit 35 DH (tarif standard EC).
export const EC_CITY_PRICING_SEED: [string, number][] = [
  ["Marrakech", 30],
  ["Casablanca", 20],
  ["Tanger", 30],
  ["Rabat", 30],
  ["Fes", 30],
  ["Agadir", 30],
  ["Meknes", 30],
  ["Kenitra", 30],
  ["Sale", 30],
  ["Oujda", 30],
  ["El jadida", 30],
  ["Temara", 30],
  ["Mohammedia", 30],
  ["Tetouan", 30],
  ["Nador", 35],
  ["Safi", 30],
  ["Beni mellal", 30],
  ["Laayoune", 35],
  ["Bouskoura", 35],
  ["Dakhla", 35],
  ["Berkane", 35],
  ["Berrechid", 35],
  ["Khouribga", 35],
  ["Kelaa seraghna", 35],
  ["Settat", 35],
  ["Dar bouazza", 35],
  ["Larache", 35],
  ["Taza", 35],
  ["Tit mellil", 35],
  ["Sale al jadida", 30],
  ["Gulmim", 35],
  ["khemisset", 35],
  ["Fkih ben salah", 35],
  ["Ait melloul", 35],
  ["Errachidia", 35],
  ["Inzegane", 35],
  ["Kser el kebir", 35],
  ["Benslimane", 35],
  ["Ouarzazate", 35],
  ["Martil", 35],
  ["Ben guerir", 35],
  ["El Hoceima", 35],
  ["Essaouira", 35],
  ["Guercif", 35],
  ["deroua", 35],
  ["Bouznika", 35],
  ["Sekhirat", 35],
  ["Tiflet", 35],
  ["Gznaya", 35],
  ["Tamesna", 35],
  ["Driouch", 35],
  ["Khenifra", 35],
  ["Sidi sliman", 35],
  ["Biougra", 35],
  ["Azilal", 35],
  ["Youssoufia", 35],
  ["Sidi bennour", 35],
  ["Souk el arbaa", 35],
  ["Ouazzane", 35],
  ["Sefrou ( fes )", 35],
  ["Sidi kasem", 35],
  ["Taourirt", 35],
  ["Azrou (ifran)", 35],
  ["Ouled nemma", 35],
  ["kasba tadla", 35],
  ["Ain harrouda", 35],
  ["Oulad teima houara", 35],
  ["Tamansourt", 35],
  ["azemmour ( El jadida )", 35],
  ["Harhoura", 35],
  ["Mediouna", 35],
  ["Selouane", 35],
  ["Taounate", 35],
  ["Taroudant", 35],
  ["Dchira", 35],
  ["Sidi bouknadel", 35],
  ["Chefchaouen", 35],
  ["Chichaoua", 35],
  ["Sidi yahya du rharb", 35],
  ["Tinghir", 35],
  ["Tiznit", 35],
  ["Zagora", 35],
  ["Ain aouda", 35],
  ["Arrahma", 35],
  ["Oued zem", 35],
  ["Had soualem", 35],
  ["Boujdour", 35],
  ["Mechra bel ksiri", 35],
  ["Tassoultant", 35],
  ["ben ahmed ( Settat )", 35],
  ["El Hajeb", 35],
  ["Ifrane", 35],
  ["Ouled berhil", 35],
  ["Ain atiq", 35],
  ["Mdiq", 35],
  ["Smara", 40],
  ["Tantan", 35],
  ["AIT Ourir", 35],
  ["imzouren", 35],
  ["Al aroui", 35],
  ["Fnideq", 35],
  ["Mrirt", 35],
  ["Midelt", 35],
  ["Nouasseur", 35],
  ["Segangan", 35],
  ["Tahla(taza)", 35],
  ["Belfaa", 35],
  ["ahfir (saidia)", 35],
  ["bir jdide", 40],
  ["Ain taoujdate ( meknes )", 35],
  ["Beni ensar", 35],
  ["Chemaia", 35],
  ["Khenichet", 35],
  ["Sidi allal el bahraoui", 35],
  ["bejaad(tadla)", 35],
  ["jourf el melha", 35],
  ["Demnate", 35],
  ["El garra ( Settat )", 35],
  ["Tahannaout", 35],
  ["Asilah", 35],
  ["Jerada", 35],
  ["Ourika", 35],
  ["El Mansouria", 40],
  ["El oualidia ( El jadida )", 35],
  ["Kariat Ba Mohamed (taounat)", 45],
  ["Layayda(rabat)", 40],
  ["Saidia", 35],
  ["Targuist", 35],
  ["kalaat mgouna", 35],
  ["Errich(midalt)", 35],
  ["Sidi ifni", 35],
  ["ghafsi (tounat)", 45],
  ["Ain chqef ( fes )", 35],
  ["BOUARFA", 35],
  ["El ksiba(tadla)", 35],
  ["Oued amlil", 35],
  ["Outat el haj(midalt)", 35],
  ["Sidi Allal Tazi ( kenitra )", 35],
  ["Tnin chtouka (jdida)", 35],
  ["Zaio", 35],
  ["moulay abdallah ( El jadida )", 35],
  ["Skhour rehamna", 35],
  ["missour(midalt)", 35],
  ["Afourar(bnimllal)", 35],
  ["Agdz", 35],
  ["Bab Berred", 45],
  ["Boumalne dades (kelaa)", 35],
  ["Moulay bousselham", 35],
  ["Ouled mrah(bnimllal)", 35],
  ["Sidi el mokhtar", 35],
  ["Tadart anza", 35],
  ["Tamelelt", 35],
  ["Tinjdad", 35],
  ["aoulouz", 35],
  ["laayoune port ( Laayoune )", 35],
  ["Akka (tata)", 45],
  ["Arfoud", 35],
  ["El aattaouia", 35],
  ["El aioun sidi mellouk", 35],
  ["El aouamra", 40],
  ["Oualmas", 35],
  ["Sabaa aiyoun ( meknes )", 35],
  ["Sidi Abdellah Ghiat", 35],
  ["Sidi rahal", 35],
  ["Taliwin", 35],
  ["Tarfaya ( Laayoune )", 35],
  ["Tighssaline", 35],
  ["Zemamra", 35],
  ["bab taza(chefchaoun)", 35],
  ["bni bouayach", 50],
  ["Amizmiz", 35],
  ["Anza(agadir)", 35],
  ["Aourir(agadir)", 35],
  ["Boufkrane", 35],
  ["Imintanoute", 40],
  ["Imouzzer Kandar", 45],
  ["Jemaa-shaim", 35],
  ["Rommani(khemissat)", 35],
  ["Sidi bouzid ( El jadida )", 35],
  ["Tamesluht", 45],
  ["Tata", 35],
  ["Temsia", 35],
  ["Zaouiat cheikh(tadla)", 35],
  ["sidi taibi (kenitra)", 35],
  ["Agourai(mknes)", 45],
  ["Ain bnimathar", 35],
  ["Aoufous", 35],
  ["Boujniba(khoribga)", 35],
  ["Boumia(midalt)", 35],
  ["Ksar sgher", 35],
  ["Midar(nador)", 35],
  ["Ouled mbarek(bnimllal)", 45],
  ["Ras el ma (saidia)", 35],
  ["Rissani", 35],
  ["Sidi bibi", 35],
  ["Tafraoute", 35],
  ["issaguen", 35],
  ["Aguelmous", 35],
  ["Alnif (tinghir)", 35],
  ["Boudnib", 35],
  ["El Afak", 40],
  ["El Borouj ( Settat )", 35],
  ["Figuig", 45],
  ["Goulmima", 35],
  ["Kaf Ennessoure", 35],
  ["Kariat Arekmane", 35],
  ["Massa", 35],
  ["Mhaya (meknes)", 45],
  ["Sebt el guerdane", 35],
  ["Sidi bou othmane", 35],
  ["Tamaresse", 35],
  ["Taznakht", 40],
  ["Tiztoutine", 35],
  ["Zaouiet Sidi Ismail", 35],
  ["ajdir(houcaima)", 35],
  ["tinzouline", 35],
  ["zoumi(ouazan)", 35],
  ["Ait Kamara", 35],
  ["Ait aamira", 35],
  ["Ait ishaq", 35],
  ["Beni Ahmed Gharbia", 40],
  ["Boulmane(midalt)", 35],
  ["Chouiter", 35],
  ["Drarga", 35],
  ["Farkhana(nador)", 35],
  ["Guigou(midalt)", 35],
  ["Mirleft", 35],
  ["Oued Laou (tetouan)", 45],
  ["Oulad ayad(bnimllal)", 35],
  ["Skoura", 35],
  ["Tamraght", 35],
  ["Tendrara", 35],
  ["Teroual(ouazan)", 35],
  ["Tissa (taounat)", 45],
  ["Zaida(midalt)", 35],
  ["ain dorij", 35],
  ["beni bouayach", 45],
  ["sidi redouane", 35],
  ["xxxx", 40],
  ["Aghbalou nserdan", 35],
  ["Ain aicha(taounat)", 35],
  ["Ain leuh(ifran)", 35],
  ["Ait Aissa Ou Brahim", 35],
  ["Ait ia\u00e0za", 35],
  ["Akka Ighane (tata)", 45],
  ["Aknoul(taza)", 40],
  ["Assa Zag", 35],
  ["Belaaguid", 30],
  ["Beni drar (saidia)", 35],
  ["Bni Hadifa", 35],
  ["Chalalt(mohmadia)", 40],
  ["El Kebab(khenifra)", 35],
  ["El Menzel(fes)", 40],
  ["Elhaj kaddour (meknes)", 35],
  ["Foum Zguid", 45],
  ["Galaz (taounat)", 50],
  ["Ghazwa", 40],
  ["Guisser (settat)", 40],
  ["Had Bouhssoussen", 35],
  ["Hattane(khoribga)", 40],
  ["Ighrem Nougdal", 35],
  ["Khemis sahel(laraich)", 35],
  ["Lalla Mimouna", 35],
  ["Lamrabta(bnimllal)", 35],
  ["Merzouga", 35],
  ["Moulay Idriss Zerhoun ( meknes )", 45],
  ["Oulad Said ( Settat )", 35],
  ["Ounara", 35],
  ["Ourtzagh(taounat)", 45],
  ["Sidi Hajjaj (settat)", 35],
  ["Sidi Jaber", 45],
  ["Sidi yahya zaer", 35],
  ["Tagzert(tadla)", 35],
  ["Tikiwine", 40],
  ["Timahdite(ifran)", 35],
  ["Tissint (tata)", 45],
  ["Tlata loulad(khoribga)", 35],
  ["Tleta El Henchane", 40],
  ["maaziz(khemissat)", 45],
  ["nkoub", 35],
  ["nzalat laadam", 35],
  ["tagounite", 35],
  ["tazarine(zagora)", 50],
];

// Tarif par défaut pour toute ville absente de la liste (35 DH = tarif standard EC).
export const EC_DEFAULT_CITY_PRICE_DH = 35;

// Tarif spécial commandes "échange" (retour/remplacement) — plat, pas lié à la ville.
export const EC_EXCHANGE_PRICE_DH = 20;
